export interface DoctorItem {
  id: string;
  name: string;
  specialization: string;
  image: any;
  rating: string;
  distance: string;
  hospital?: string;
  fee?: string;
  availability?: string;
  about?: string;
  experience?: string;
  reviewsCount?: number;
  experienceYears?: number;
  patientsCount?: number;
}

// Top Doctors sorted rating-wise (Highest rating first)
export const DOCTORS_DATA: DoctorItem[] = [
  {
    id: '1',
    name: 'Dr. Maria Elena',
    specialization: 'Psychologist',
    image: require('../assets/images/home/doctors/maria-elena.png'),
    rating: '4.9',
    distance: '1.5km away',
    hospital: 'City Care Medical Center',
    fee: '$90.00',
    availability: 'Available Today',
    experience: '6 Years',
    about: 'Dr. Maria Elena specializes in cognitive behavioral therapy, anxiety management, and mindfulness-based stress relief.',
    reviewsCount: 189,
    experienceYears: 6,
    patientsCount: 1220,
  },
  {
    id: '2',
    name: 'Dr. Gerty Horizon',
    specialization: 'Pediatrician',
    image: require('../assets/images/home/doctors/doctor-gerty.png'),
    rating: '4.9',
    distance: '1.2km away',
    hospital: 'Sunrise Community Hospital',
    fee: '$95.00',
    availability: 'Available Today',
    experience: '7 Years',
    about: 'Dr. Gerty Horizon has dedicated 7 years to neonatal and pediatric wellness, child immunizations, and developmental health.',
    reviewsCount: 167,
    experienceYears: 7,
    patientsCount: 980,
  },
  {
    id: '3',
    name: 'Dr. Alexander Reed',
    specialization: 'Neurologist',
    image: require('../assets/doctor1.png'),
    rating: '4.9',
    distance: '1.8km away',
    hospital: 'Metro Health Super Specialty',
    fee: '$135.00',
    availability: 'Available Today',
    experience: '12 Years',
    about: 'Dr. Alexander Reed is an expert neurologist specializing in migraine therapies, stroke rehabilitation, and neuro-diagnostics.',
    reviewsCount: 240,
    experienceYears: 12,
    patientsCount: 2100,
  },
  {
    id: '4',
    name: 'Dr. Stefi Jessi',
    specialization: 'Orthopedist',
    image: require('../assets/images/home/doctors/stefi-jessi.png'),
    rating: '4.8',
    distance: '2.0km away',
    hospital: 'Grace Memorial Hospital',
    fee: '$110.00',
    availability: 'Available Tomorrow',
    experience: '10 Years',
    about: 'Dr. Stefi Jessi is an expert orthopedic surgeon specializing in sports injuries, joint health, and musculoskeletal rehabilitation.',
    reviewsCount: 215,
    experienceYears: 10,
    patientsCount: 2050,
  },
  {
    id: '5',
    name: 'Dr. Sophia Chen',
    specialization: 'Dermatologist',
    image: require('../assets/doctor2.png'),
    rating: '4.8',
    distance: '900m away',
    hospital: 'Apollo Speciality Hospital',
    fee: '$105.00',
    availability: 'Available Today',
    experience: '9 Years',
    about: 'Dr. Sophia Chen is a board-certified dermatologist focusing on clinical dermatology, allergy testing, and acne treatments.',
    reviewsCount: 178,
    experienceYears: 9,
    patientsCount: 1640,
  },
  {
    id: '6',
    name: 'Dr. Rajesh Varma',
    specialization: 'Pulmonologist',
    image: require('../assets/doctor3.png'),
    rating: '4.8',
    distance: '2.3km away',
    hospital: 'City Care Medical Center',
    fee: '$115.00',
    availability: 'Available Tomorrow',
    experience: '11 Years',
    about: 'Dr. Rajesh Varma is a senior pulmonologist specializing in respiratory disorders, asthma management, and lung care.',
    reviewsCount: 195,
    experienceYears: 11,
    patientsCount: 1820,
  },
  {
    id: '7',
    name: 'Dr. Marcus Horizon',
    specialization: 'Cardiologist',
    image: require('../assets/images/home/doctors/marcus-horizon.png'),
    rating: '4.7',
    distance: '800m away',
    hospital: 'Apollo Speciality Hospital',
    fee: '$120.00',
    availability: 'Available Today',
    experience: '8 Years',
    about: 'Dr. Marcus Horizon is a senior cardiologist with 8+ years of clinical experience in non-invasive cardiology and preventative heart care.',
    reviewsCount: 142,
    experienceYears: 8,
    patientsCount: 1540,
  },
  {
    id: '8',
    name: 'Dr. Emily Watson',
    specialization: 'General Physician',
    image: require('../assets/doctor1.png'),
    rating: '4.7',
    distance: '1.1km away',
    hospital: 'Grace Memorial Hospital',
    fee: '$80.00',
    availability: 'Available Today',
    experience: '8 Years',
    about: 'Dr. Emily Watson provides comprehensive primary healthcare, preventative health screenings, and fever/lifestyle consultations.',
    reviewsCount: 156,
    experienceYears: 8,
    patientsCount: 1400,
  },
  {
    id: '9',
    name: 'Dr. David Miller',
    specialization: 'ENT Specialist',
    image: require('../assets/doctor2.png'),
    rating: '4.7',
    distance: '2.8km away',
    hospital: 'Sunrise Community Hospital',
    fee: '$100.00',
    availability: 'Available Today',
    experience: '7 Years',
    about: 'Dr. David Miller specializes in ear, nose, throat, sinus issues, audiology diagnostics, and allergy relief.',
    reviewsCount: 134,
    experienceYears: 7,
    patientsCount: 1100,
  },
  {
    id: '10',
    name: 'Dr. Diandra',
    specialization: 'Dentist',
    image: require('../assets/images/home/doctors/doctor-diandra.png'),
    rating: '4.6',
    distance: '2.5km away',
    hospital: 'Metro Health Super Specialty',
    fee: '$85.00',
    availability: 'Available Tomorrow',
    experience: '5 Years',
    about: 'Dr. Diandra offers advanced cosmetic and restorative dentistry with gentle, modern pediatric & adult dental therapies.',
    reviewsCount: 112,
    experienceYears: 5,
    patientsCount: 850,
  },
];
