export interface MedicineItem {
  id: string;
  name: string;
  category: string;
  dosage: string;
  price: number;
  originalPrice: number;
  inStock: boolean;
  requiresPrescription: boolean;
  description: string;
  image?: any;
}

export const MEDICINES_DATA: MedicineItem[] = [
  {
    id: 'm1',
    name: 'Paracetamol 650mg',
    category: 'Pain Relief',
    dosage: '10 Tablets Strip',
    price: 3.50,
    originalPrice: 4.50,
    inStock: true,
    requiresPrescription: false,
    description: 'Fast acting antipyretic and analgesic for fever, mild body aches, and headaches.',
  },
  {
    id: 'm2',
    name: 'Amoxicillin 500mg',
    category: 'Tablets',
    dosage: '6 Capsules Strip',
    price: 8.20,
    originalPrice: 10.00,
    inStock: true,
    requiresPrescription: true,
    description: 'Broad-spectrum antibiotic for bacterial ear, chest, and throat infections.',
  },
  {
    id: 'm3',
    name: 'Ibuprofen 400mg',
    category: 'Pain Relief',
    dosage: '10 Tablets Strip',
    price: 4.80,
    originalPrice: 6.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Non-steroidal anti-inflammatory drug (NSAID) for muscle soreness and inflammation.',
  },
  {
    id: 'm4',
    name: 'Vitamin C 1000mg + Zinc',
    category: 'Vitamins',
    dosage: '20 Effervescent Tabs',
    price: 12.00,
    originalPrice: 15.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Daily immune system booster and powerful antioxidant with pleasant orange flavor.',
  },
  {
    id: 'm5',
    name: 'Cetirizine 10mg',
    category: 'Tablets',
    dosage: '10 Tablets Strip',
    price: 3.00,
    originalPrice: 4.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Second-generation antihistamine providing 24h relief from allergies and rhinitis.',
  },
  {
    id: 'm6',
    name: 'Herbal Cough & Throat Syrup',
    category: 'Syrups',
    dosage: '100ml Bottle',
    price: 6.50,
    originalPrice: 8.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Non-drowsy soothing herbal formulation with Honey, Tulsi, and Ginger.',
  },
  {
    id: 'm7',
    name: 'Digital Oral Thermometer',
    category: 'First Aid',
    dosage: '1 Unit Device',
    price: 9.50,
    originalPrice: 12.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Fast 10-second accurate fever reading with LCD backlight and fever alarm.',
  },
  {
    id: 'm8',
    name: 'Antiseptic First Aid Bandages',
    category: 'First Aid',
    dosage: '50 Adhesive Strips',
    price: 4.00,
    originalPrice: 5.50,
    inStock: true,
    requiresPrescription: false,
    description: 'Sterile waterproof adhesive bandages for minor cuts, scrapes, and blisters.',
  },
  {
    id: 'm9',
    name: 'Omeprazole 20mg Capsules',
    category: 'Digestive',
    dosage: '14 Capsules Strip',
    price: 7.50,
    originalPrice: 9.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Proton pump inhibitor for acid reflux, heartburn relief, and indigestion.',
  },
  {
    id: 'm10',
    name: 'Gelusil Antacid Liquid',
    category: 'Digestive',
    dosage: '200ml Bottle',
    price: 5.20,
    originalPrice: 6.50,
    inStock: true,
    requiresPrescription: false,
    description: 'Fast relief from acidity, gas, bloating, and stomach discomfort.',
  },
  {
    id: 'm11',
    name: 'Hydrocortisone 1% Cream',
    category: 'Skin Care',
    dosage: '30g Tube',
    price: 6.80,
    originalPrice: 8.50,
    inStock: true,
    requiresPrescription: false,
    description: 'Topical soothing cream for skin irritation, eczema, insect bites, and redness.',
  },
  {
    id: 'm12',
    name: 'Soothing Aloe Vera Healing Gel',
    category: 'Skin Care',
    dosage: '100g Jar',
    price: 5.50,
    originalPrice: 7.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Pure cooling aloe vera gel for sunburn, rash relief, and daily skin hydration.',
  },
  {
    id: 'm13',
    name: 'Multivitamin Complete Daily',
    category: 'Vitamins',
    dosage: '60 Chewable Tablets',
    price: 14.50,
    originalPrice: 18.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Essential daily vitamins A, B-complex, D3, E, and minerals for energy & focus.',
  },
  {
    id: 'm14',
    name: 'Dextromethorphan Dry Cough Relief',
    category: 'Syrups',
    dosage: '100ml Syrup',
    price: 7.20,
    originalPrice: 9.00,
    inStock: true,
    requiresPrescription: false,
    description: 'Clinically proven antitussive syrup to suppress stubborn dry coughs.',
  },
  {
    id: 'm15',
    name: 'Diclofenac Fast Relief Gel',
    category: 'Pain Relief',
    dosage: '30g Tube',
    price: 5.90,
    originalPrice: 7.50,
    inStock: true,
    requiresPrescription: false,
    description: 'Targeted joint, knee, and back pain relief with fast deep-penetrating action.',
  },
  {
    id: 'm16',
    name: 'Azithromycin 500mg',
    category: 'Tablets',
    dosage: '3 Tablets Strip',
    price: 9.80,
    originalPrice: 12.50,
    inStock: true,
    requiresPrescription: true,
    description: 'Antibiotic for upper respiratory tract and throat infections.',
  },
];
