import { AppointmentItem } from '../components/bottomTab/schedule/AppointmentCard';
import { DOCTORS_DATA } from './doctorsData';

export const DOCTOR_AVATARS: Record<string, any> = {
  'Dr. Marcus Horizon': require('../assets/images/home/doctors/marcus-horizon.png'),
  'Dr. Maria Elena': require('../assets/images/home/doctors/maria-elena.png'),
  'Dr. Stefi Jessi': require('../assets/images/home/doctors/stefi-jessi.png'),
  'Dr. Gerty Cori': require('../assets/images/home/doctors/doctor-gerty.png'),
  'Dr. Diandra': require('../assets/images/home/doctors/doctor-diandra.png'),
};

export const getDoctorAvatar = (doctorName: string, fallback?: any) => {
  if (DOCTOR_AVATARS[doctorName]) return DOCTOR_AVATARS[doctorName];
  const doc = DOCTORS_DATA.find((d) => d.name.toLowerCase() === doctorName.toLowerCase());
  if (doc && doc.image) return doc.image;
  return fallback || DOCTOR_AVATARS['Dr. Marcus Horizon'];
};

export const INITIAL_APPOINTMENTS: AppointmentItem[] = [
  {
    id: '1',
    doctorName: 'Dr. Marcus Horizon',
    specialization: 'Cardiologist',
    avatar: require('../assets/images/home/doctors/marcus-horizon.png'),
    rating: '4.7',
    date: '26/06/2026',
    time: '10:30 AM',
    status: 'upcoming',
    statusLabel: 'Confirmed',
    hospitalName: 'City Care Hospital',
    consultationType: 'Video Call',
    bookingId: '#MED-18921',
    patientName: 'Sathish Kumar',
    patientAge: '28 yrs',
    patientGender: 'Male',
    fee: '$50.00',
    problemDescription: 'Routine cardiac health review and discussion on mild chest tightness during morning workouts.',
  },
  {
    id: '2',
    doctorName: 'Dr. Maria Elena',
    specialization: 'Psychologist',
    avatar: require('../assets/images/home/doctors/maria-elena.png'),
    rating: '4.9',
    date: '28/06/2026',
    time: '02:00 PM',
    status: 'upcoming',
    statusLabel: 'Confirmed',
    hospitalName: 'Sunrise Hospital',
    consultationType: 'Video Call',
    bookingId: '#MED-28922',
    patientName: 'Sathish Kumar',
    patientAge: '28 yrs',
    patientGender: 'Male',
    fee: '$60.00',
    problemDescription: 'Stress management consultation and sleep routine improvement strategies.',
  },
  {
    id: '3',
    doctorName: 'Dr. Stefi Jessi',
    specialization: 'Orthopedist',
    avatar: require('../assets/images/home/doctors/stefi-jessi.png'),
    rating: '4.8',
    date: '15/05/2026',
    time: '11:00 AM',
    status: 'completed',
    statusLabel: 'Completed',
    hospitalName: 'Apollo Hospital',
    consultationType: 'Hospital Visit',
    bookingId: '#MED-38923',
    patientName: 'Sathish Kumar',
    patientAge: '28 yrs',
    patientGender: 'Male',
    fee: '$45.00',
    diagnosis: 'Mild lumbar strain and posture fatigue. Recommended ergonomic adjustments.',
    prescriptions: [
      { medicine: 'Ibuprofen 400mg', dosage: '1 tablet as needed with food', duration: '5 days' },
      { medicine: 'Muscle Relaxant Cream', dosage: 'Apply thin layer twice daily', duration: '7 days' },
    ],
  },
  {
    id: '4',
    doctorName: 'Dr. Gerty Cori',
    specialization: 'General Specialist',
    avatar: require('../assets/images/home/doctors/doctor-gerty.png'),
    rating: '4.7',
    date: '10/05/2026',
    time: '04:30 PM',
    status: 'completed',
    statusLabel: 'Completed',
    hospitalName: 'City Care Hospital',
    consultationType: 'Video Call',
    bookingId: '#MED-48924',
    patientName: 'Sathish Kumar',
    patientAge: '28 yrs',
    patientGender: 'Male',
    fee: '$40.00',
    diagnosis: 'Seasonal allergic rhinitis with mild throat irritation.',
    prescriptions: [
      { medicine: 'Cetirizine 10mg', dosage: '1 tablet before bedtime', duration: '10 days' },
      { medicine: 'Vitamin C 500mg', dosage: '1 chewable daily after lunch', duration: '15 days' },
    ],
  },
  {
    id: '5',
    doctorName: 'Dr. Diandra',
    specialization: 'Dentist',
    avatar: require('../assets/images/home/doctors/doctor-diandra.png'),
    rating: '4.7',
    date: '02/04/2026',
    time: '09:00 AM',
    status: 'canceled',
    statusLabel: 'Canceled',
    hospitalName: 'Dental Care Clinic',
    consultationType: 'Hospital Visit',
    bookingId: '#MED-58925',
    patientName: 'Sathish Kumar',
    patientAge: '28 yrs',
    patientGender: 'Male',
    fee: '$35.00',
    cancelReason: 'Appointment canceled due to change in schedule.',
  },
];
